// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCl6fLWxABvltLD0OaQ7dKpmmUmEizwofk',
    appId: '1:548950474130:web:045c663e6b8f64f277d54b',
    messagingSenderId: '548950474130',
    projectId: 'itigroup3-b1b7d',
    authDomain: 'itigroup3-b1b7d.firebaseapp.com',
    storageBucket: 'itigroup3-b1b7d.appspot.com',
    measurementId: 'G-1KQK2E13J2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAiXTd_TvStBkFGOv9ArCossrP8rzXn0vo',
    appId: '1:548950474130:android:7ba0379416cd297377d54b',
    messagingSenderId: '548950474130',
    projectId: 'itigroup3-b1b7d',
    storageBucket: 'itigroup3-b1b7d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAUbkH1n7r-nKq9S26xXPkZPep6UD9LK5Q',
    appId: '1:548950474130:ios:89c0e622fe952f0e77d54b',
    messagingSenderId: '548950474130',
    projectId: 'itigroup3-b1b7d',
    storageBucket: 'itigroup3-b1b7d.appspot.com',
    iosClientId: '548950474130-qm6dlp1oa8gde6j5nimn4i2gqg3u56i5.apps.googleusercontent.com',
    iosBundleId: 'com.example.loginDesign',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAUbkH1n7r-nKq9S26xXPkZPep6UD9LK5Q',
    appId: '1:548950474130:ios:d9908f372d392edd77d54b',
    messagingSenderId: '548950474130',
    projectId: 'itigroup3-b1b7d',
    storageBucket: 'itigroup3-b1b7d.appspot.com',
    iosClientId: '548950474130-gq51tuibeneok36cl7kd8or77356mvld.apps.googleusercontent.com',
    iosBundleId: 'com.example.loginDesign.RunnerTests',
  );
}
